# Generated by Django 2.2.7 on 2019-11-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jam',
            name='content',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
