# Generated by Django 2.2.7 on 2019-11-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0003_jam_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jam', to='jam.Project'),
        ),
    ]
