# Generated by Django 2.2.7 on 2019-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0004_auto_20191130_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jam',
            name='prelevel',
            field=models.IntegerField(default=0),
        ),
    ]
