# Generated by Django 2.2.7 on 2019-11-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0005_auto_20191130_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jam',
            old_name='prelevel',
            new_name='depth',
        ),
        migrations.AddField(
            model_name='jam',
            name='orderno',
            field=models.IntegerField(default=0),
        ),
    ]
