# Generated by Django 2.2.7 on 2019-11-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0006_auto_20191201_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jam',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='jam',
            name='orderno',
        ),
        migrations.AddField(
            model_name='jam',
            name='jjam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jam.Jam'),
        ),
        migrations.AlterField(
            model_name='jam',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jams', to='jam.Project'),
        ),
    ]
