# Generated by Django 2.2.4 on 2019-11-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0007_auto_20191201_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jam',
            name='jjam',
        ),
    ]
