# Generated by Django 2.2.7 on 2019-11-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0009_auto_20191201_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jam',
            name='inst',
            field=models.CharField(choices=[('vocal', 'vocal'), ('drum', 'drum'), ('elec', 'elec'), ('piano', 'piano'), ('bass', 'bass'), ('other', 'other')], max_length=20),
        ),
    ]
